#!/bin/bash
mkdir -p dist
cd dist

# Run emconfigure with the normal configure command as an argument.
emconfigure cmake ../open-vcdiff -DCMAKE_BUILD_TYPE=Debug

# Run emmake with the normal make to generate linked LLVM bitcode.
emmake make

# Compile the linked bitcode generated by make (project.bc) to JavaScript.
#  'project.bc' should be replaced with the make output for your project (e.g. 'yourproject.so')
#  [-Ox] represents build optimisations (discussed in the next section).
export CPATH=$PWD/../open-vcdiff/src

emcc -O3 -s WASM=1 -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap"]' ../compat/vcdenc.cc libvcdenc.a libvcdcom.a -o libvcdenc.js
emcc -O3 -s WASM=1 -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap"]' ../compat/vcddec.cc libvcddec.a libvcdcom.a -o libvcddec.js